title: "L-Systems"
author: "Aleksander Tudruj"
link: "https://github.com/tudny/GK-projekt-zaliczeniowy"
description: |
  Projekt prezentuje proste L-Systemy napisane w OpenGLu.
images:
  - "window.png"
