name: Create release package

on:
  release:
    types: [published]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build application
      run: make pack
    - name: upload release package
      uses: softprops/action-gh-release@v2
      with:
        files: projekty-z-grafiki.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ github.event.release.body }}
